### ISSUE TITLE
Missing template

### ISSUE THREAD

**Issue by libelle** [jmbjorndalen/scedit#1]
Hi! Just trying to set this up for my niece & nephew's Scriptcraft server. It looks like it will do exactly what they need to be able to learn more complex JS.

When I start it up, however, I run into the problem that I can't log in. It looks like one or more files didn't get committed into the repo.

> Error: 500 Internal Server Error
> 
> Sorry, the requested URL 'http://myserver:8095/login' caused an error:
> 
> Template 'login_form' not found.

**Comment by jmbjorndalen** [comment]
Hi. I'm sorry for letting you wait this long. I have somehow managed to miss this issue  :-/ 

The problem was a missing login template. I have added that to the repository now.
